language: ruby

rvm:
  - 2.2.0

gemfile:
  - Gemfile

services:
  - docker

before_install:
  - gem install bundler

script:
  - docker-compose up
  #bundle exec rake docker["api"]

branches:
  only:
    - live
