version: "2"

services:
  voting-app:
    image: irfanah/example-voting-app
    volumes:
     - /app
    ports:
      - "5000:80"
    links:
      - redis
    networks:
      - front-tier
      - back-tier

  result-app:
    image: irfanah/example-result-app
    volumes:
      - /app
    ports:
      - "5001:80"
    links:
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    image: irfanah/worker
    links:
      - db
      - redis
    networks:
      - back-tier

  redis:
    image: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  hub:
    image: selenium/hub:2.53.0
    ports:
       - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug:2.53.0
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5900:5900"
    links:
      - hub

  firefox:
    image: selenium/node-firefox-debug:2.53.0
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5901:5900"
    links:
      - hub

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
