<%
  config_requires        = "--require config --require step_definitions/api"
  mobile_requires        = config_requires + "--require step_definitions/mobile"
  forumapi_requires      = config_requires + "--require step_definitions/api"
  smoke_requires         = "--require config --require step_definitions/smoke"
  production_requires    = "--require config --require step_definitions/posweb"
  pending_requires       = "--require config --require step_definitions/posweb"
%>


default    : <%= config_requires %> --format pretty
mobile     : <%= mobile_requires %> --format progress --tags @mobile
forumapi   : <%= forumapi_requires %> --format json -o cucumber.json --format pretty --tags @forumapi
smoke      : <%= smoke_requires %> --format html --out reports/pending_report.html --format pretty  --tags @smoke
production : <%= production_requires %> --format json -o cucumber.json --format pretty --tags @production
pending    : <%= pending_requires %> --format html --out reports/pending_report.html --format pretty --tags @pending

#old: SERVER= "https://example.com"

#for rerun use below options
#$​cucumber -f pretty -f html --out report.html -f rerun --out rerun.txt​
