<%
  config_requires        = "--require config --require step_definitions/api"
  web_requires           = "--require config --require step_definitions/web"
  api_requires           = "--require config --require step_definitions/api"
%>


default    : <%= config_requires %> --format json -o cucumber.json --format pretty
web        : <%= web_requires %> --format json -o cucumber.json --format pretty --format html --out report.html  --tags @web
api        : <%= api_requires %> --format json -o cucumber.json --format pretty --format html --out report.html --tags @api
